premium_features:
  shout_cooldown: 86400
  premium_slot_start: 200
  premium_store_link: 'https://store.playares.com'
tab_display:
  header:
    - 'Welcome to Ares'
  footer:
    - 'playares.com'
motd:
  server_list:
    - '&4&lAres'
    - '&7Server Announcement coming April 18th'
  join:
    - '&7&m------------------------------'
    - '&r '
    - '&fWelcome to &4Ares'
    - '&r '
    - '&r &f⇨&r &cWebsite&f: https://www.playares.com'
    - '&r &f⇨&r &cDiscord&f: https://discord.playares.com'
    - '&r &f⇨&r &cStore&f: https://store.playares.com'
    - '&r &f⇨&r &cReddit&f: https://reddit.com/r/Ares'
    - '&r '
    - '&7&m------------------------------'